FROM registry.access.redhat.com/ubi8:8.5

MAINTAINER Ahmed Shendy <amshendi.c@stc.com.sa>

LABEL description="A custom Apache container based on UBI 8"

RUN yum install -y httpd && \
    yum clean all

RUN echo "Hello from Containerfile" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]
